project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('users/', include('users.urls')),
    path('repairs/', include('repairs.urls'), name='repairs'),
]

repairs/urls.py
from django.urls import path

from repairs.views import CreateRepair, RepairList, DetailRepair


app_name = 'repairs'

urlpatterns = [
    path('', RepairList.as_view(), name='list'),
    path('create/', CreateRepair.as_view(), name='create'),
    path('detail/<int:repair_id>', DetailRepair.as_view(), name='detail'),
]

users/urls.py
from django.urls import path, include

from users.views import Register

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', Register.as_view(), name='register'),
]

repairs/models/locomotives.py
from django.db import models


class Locomotive(models.Model):
    name = models.CharField(max_length=55, verbose_name='Назва локомотиву')

    class Meta:
        verbose_name = 'Локомотив'
        verbose_name_plural = 'Локомотиви'

    def __str__(self):
        return self.name

repairs/models/parts.py
from django.db import models


class Parts(models.Model):
    name = models.CharField(max_length=255, verbose_name='Назва деталі')

    class Meta:
        verbose_name = 'Деталь'
        verbose_name_plural = 'Деталі'

    def __str__(self):
        return self.name

repairs/models/places.py
from django.db import models


class PlacesToWork(models.Model):
    name = models.CharField(max_length=255, verbose_name='Назва місця')

    class Meta:
        verbose_name = 'Місце роботи'
        verbose_name_plural = 'Місця роботи'

    def __str__(self):
        return self.name

repairs/models/repair_type.py
from django.db import models


class RepairType(models.Model):
    name = models.CharField(max_length=255, verbose_name='Назва типу ремонту')
    hours = models.IntegerField(verbose_name='Кількість годин ремонту')

    class Meta:
        verbose_name = 'Тип ремонту'
        verbose_name_plural = 'Типи ремонту'

    def __str__(self):
        return self.name

repairs/models/repairs.py
from django.db import models
from django.urls import reverse

class Status(models.TextChoices):
    """"Statuses for repairs"""
    CREATED = 'CREATED', 'Created'
    CONFIRMED = 'CONFIRMED', 'Confirmed'
    READY_TO_WORK = 'READY_TO_REPAIR', 'Ready to repair'
    PROGRESS = 'PROGRESS', 'In progress'
    VERIFICATION = 'VERIFICATION', 'Verification'
    TEST = 'TEST', 'Test'
    RE_REPAIR = 'RE_REPAIR', 'Re-repair'



class Repair(models.Model):
    users = models.ManyToManyField(to='users.User', related_name='repairs', verbose_name='Заявники')
    description = models.TextField(verbose_name='Опис поломки')
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.CREATED, verbose_name='Статус')
    time_to_work = models.DateTimeField(verbose_name='Час початку ремонту', null=True, blank=True)

    places_to_work = models.ForeignKey('repairs.PlacesToWork', related_name='place_repairs', verbose_name='Місця роботи',
                                       null=True, blank=True, on_delete=models.PROTECT)
    locomotive = models.ForeignKey('repairs.Locomotive', related_name='locomotive_repairs', verbose_name='Локомотив',
                                  null=True, blank=True, on_delete=models.PROTECT)
    repair_type = models.ForeignKey('repairs.RepairType', related_name='type_repairs', verbose_name='Тип ремонту',
                                    null=True, blank=True, on_delete=models.PROTECT)
    works = models.ManyToManyField(to='repairs.Works', related_name='work_repairs', verbose_name='Роботи')
    parts = models.ManyToManyField(to='repairs.Parts', related_name='parts_repairs', verbose_name='Деталі')

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'

    def __str__(self):
        return f'Заявка: {self.id}'
    
    def get_absolute_url(self):
        return reverse("repairs:detail", kwargs={"repair_id": self.pk})
    

repairs/models/works.py
from django.db import models


class Works(models.Model):
    name = models.CharField(max_length=255, verbose_name='Назва роботи')
    repair_type = models.ForeignKey('repairs.RepairType', on_delete=models.CASCADE, related_name='works', 
                                    null=True, blank=True)

    class Meta:
        verbose_name = 'Робота'
        verbose_name_plural = 'Роботи'

    def __str__(self):
        return self.name

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class Role(models.TextChoices):
    CUSTOMER = 'CUSTOMER', 'Customer'
    TECHNICIAN = 'TECHNICIAN', 'Technician'
    MASTER = 'MASTER', 'Master'
    WORKER = 'WORKER', 'Worker'


class User(AbstractUser):
    role = models.CharField(max_length=15, choices=Role.choices, default=Role.CUSTOMER)
    email = models.EmailField(_('email address'), max_length=50, unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

repairs/forms/customer.py
from django import forms

from repairs.models import Repair, Locomotive


class CustomerForm(forms.ModelForm):
    description = forms.CharField(label='Опис поломки', widget=forms.Textarea(attrs={'class': 'form-control','rows': 5, 'cols': 40}))
    locomotive = forms.ModelChoiceField(label='Виберіть локомотив', 
                                        queryset=Locomotive.objects.all(), 
                                        widget=forms.Select())
    
    class Meta:
        model = Repair
        fields = ('description', 'locomotive')

repairs/forms/master.py
from django import forms
from django.contrib.auth import get_user_model

from repairs.models import Repair, Parts, Status
from users.models import Role

User = get_user_model()


class MasterForm(forms.ModelForm):
    """Form for work with order for master"""
    parts = forms.ModelMultipleChoiceField(
        label='Деталі',
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),
        queryset=Parts.objects.all(),
    )

    users = forms.ModelMultipleChoiceField(
        label='Workers',
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}),
        queryset=User.objects.filter(role=Role.WORKER),
    )
    status = forms.ChoiceField(
        label='Статус',
        widget=forms.Select(attrs={'class': 'form-control'}),
        choices=[
            item for item in Status.choices if item[0] in ('READY_TO_WORK', 'RE_REPAIR', 'VERIFICATION')
        ]
    )

    class Meta:
        model = Repair
        fields = ('parts', 'users', 'status')

repairs/forms/technician.py
from django import forms

from repairs.models import Repair, PlacesToWork, RepairType, Status


class TechnicianForm(forms.ModelForm):
    """Form for work with order for technician"""
    description = forms.CharField(
        label='Опис поломки', 
        widget=forms.Textarea(attrs={'class': 'form-control','rows': 5, 'cols': 40})
    )
    time_to_work = forms.DateTimeField(
        label='Час початку ремонту', 
        widget=forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'})
    )
    places_to_work = forms.ModelChoiceField(
        label='Місце роботи',
        widget=forms.Select(attrs={'class': 'form-control'}),
        queryset=PlacesToWork.objects.all(),               
    )
    repair_type = forms.ModelChoiceField(
        label='Тип ремонту',
        widget=forms.Select(attrs={'class': 'form-control'}),
        queryset=RepairType.objects.all(),
    )
    status = forms.ChoiceField(
        label='Статус',
        widget=forms.Select(attrs={'class': 'form-control',}),
        choices=[
            item for item in Status.choices if item[0] == Status.CONFIRMED
        ]
    )
    
    class Meta:
        model = Repair
        fields = (
            'description',
            'time_to_work',
            'places_to_work',
            'repair_type',
            'status',
            )

repairs/forms/worker.py
from django import forms

from repairs.models import Repair, Status


class WorkerForm(forms.ModelForm):
    """Form for work with order for worker"""
    status = forms.ChoiceField(
        label='Статус',
        widget=forms.Select(attrs={'class': 'form-control'}),
        choices=[
            item for item in Status.choices if item[0] in ('PROGRESS', 'TEST')
        ]
    )

    class Meta:
        model = Repair
        fields = ('status',)

repairs/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model
from django.views.generic import ListView, FormView
from django.views import View
from django import forms

from repairs.mixins import RepairMixin
from repairs.forms.customer import CustomerForm
from repairs.forms.technician import TechnicianForm
from repairs.forms.master import MasterForm
from repairs.forms.worker import WorkerForm
from repairs.models import Status, Repair
from users.models import Role


class RepairList(RepairMixin, ListView):
    """"List of repairs"""
    template_name = 'repair_list.html'
    model = Repair
    paginate_by = 5


    def get_queryset(self):
        _filter = self._get_repair_filter(self.request.user)
        return Repair.objects.filter(**_filter)


class CreateRepair(FormView):
    template_name = 'create_repair.html'
    form_class = CustomerForm
    success_url = "/repairs/"

    def form_valid(self, form):
        repair = form.save()
        repair.users.add(self.request.user)
        return super().form_valid(form)
    

class DetailRepair(RepairMixin, View):
    """"Repair detail"""
    template_name = 'detail.html'

    def _get_form(self, repair, data=None) -> forms.ModelForm:
        """Return form according to user role"""
        user_form = {
            Role.CUSTOMER: None, 
            Role.TECHNICIAN: TechnicianForm(data=data, instance=repair, initial={'status': 'CONFIRMED'}),
            Role.MASTER: MasterForm(data=data, instance=repair),
            Role.WORKER: WorkerForm(data=data, instance=repair),
            }
        return user_form.get(self.request.user.role)

    def post(self, request, repair_id):
        _filter = self._get_repair_filter(self.request.user)
        repair = get_object_or_404(Repair, pk=repair_id, **_filter)
        form = self._get_form(repair, data=request.POST)
        if form.is_valid():
            # users = form.cleaned_data['users']
            users = list(repair.users.all())
            form.save()
            repair.users.add(request.user, *users)
        context = {'repair': repair, 'form': form,}
        return render(request, self.template_name, context)

    def get(self, request, repair_id):
        _filter = self._get_repair_filter(self.request.user)
        repair = get_object_or_404(Repair, pk=repair_id, **_filter)
        context = {'repair': repair, 'form': self._get_form(repair),}
        return render(request, self.template_name, context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>User authenticate</title>
</head>

<body>
    <div class="container ">

        <ul class="list-group">
            <li class="list-group-item">
                User: {{ user }} | Role: {{ user.get_role_display }}
            </li>
            <li class="list-group-item">
                <a href="{% url 'home' %}">Home</a> | <a href="{% url 'repairs:list' %}">Zaiavka</a>
            </li>
        </ul>

    </div>
    

{% block content %}
{% endblock %}

</body>
</html>

templates/create_repair.html
{% extends "base.html" %} 

{% block content %}

<div class="container">
    <h2>Форма заявки на ремонт</h2>
    <form class="" action="{% url 'repairs:create' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-success m-1" type="submit">Створити заявку</button>
        
    </form>

</div>

{% endblock %}

templates/detail.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row mt-2">
        <div class="col-md-12">
            <h2>Order Details</h2>
        </div>
        <hr>
        {% include "repair.html" with repair=repair %}
    </div>
    <form action="" method="post">
        {% csrf_token %} 
        {{ form }}
        <button class="btn btn-success" type="submit">Update</button>
    </form>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="bg-info">Home page</h1>
    <hr>

    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a> |
        <a href="{% url 'register' %}">Register</a>
    {% endif %}
{% endblock %}

templates/repair.html
<ul class="list-unstyled">
    <li><strong>Description: </strong>{{ repair.description }}</li>
    <li>
        <strong>Involved: </strong>
        <ul>
            {% for user in repair.users.all %}
            <li><strong>{{ user.get_role_display }}</strong> - {{ user.first_name }} {{ user.last_name }}: {{ user.email }}</li>
            {% endfor %}
        </ul>
    </li>
    <li><strong>Locomotive: </strong>{{ repair.locomotive }}</li>
    {% if repair.places_to_work %}
        <li><strong>Place of repair: </strong>{{ repair.places_to_work }}</li>
    {% endif %}
    {% if repair.time_to_work %}
        <li><strong>Time of repair: </strong>{{ repair.time_to_work }}</li>
    {% endif %}
    {% if repair.type_repair %}
        <li><strong>Type of repair: </strong>{{ repair.type_repair }}</li>
    {% endif %}
    {% if repair.parts %}
        <strong>Spare parts: </strong>
        <ul>
            {% for part in repair.parts.all %}
                <li>{{ part.name }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <li><strong>Status: </strong>{{ repair.get_status_display }}</li>
    
</ul>

templates/repair_list.html
{% extends "base.html" %} 

{% block content %}
<div class="container">
    <h2>Заявка на ремонт</h2>
    <a class="btn btn-success" href="{% url 'repairs:create' %}">Створити заявку</a>


    <div class="row mt-2">
        <div class="col-md-12">
            <table class="table table-success table-striped">
                <thead>
                    <tr>
                        <th>Order number</th>
                        <th>Locomotive</th>
                        <th>Repair place</th>
                        <th>Repair type</th>
                        <th>Date and time </th>
                        <th>Status</th>
                        <th>Open</th>
                    </tr>
                </thead>
                <tbody>
                    {% for repair in object_list %}
                    <tr>
                        <td>{{ repair.id }}</td>
                        <td>{{ repair.locomotive }}</td>
                        {% if repair.places_to_work %}
                            <td>{{ repair.places_to_work }}</td>
                        {% else %}
                            <td>Isn't defined</td>
                        {% endif %}
                        {% if repair.repair_type %}
                            <td>{{ repair.repair_type }}</td>
                        {% else %}
                            <td>Isn't defined</td>
                        {% endif %}
                        {% if repair.time_to_work %}
                            <td>{{ repair.time_to_work }}</td>
                        {% else %}
                            <td>Isn't defined</td>
                        {% endif %}
                        <td>{{ repair.get_status_display }}</td>
                        <td>
                            <a href="{{ repair.get_absolute_url }}">Open</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            
            </table>
        </div>
    </div>

</div>

{% endblock %}

templates/repairs.html
{% extends 'base.html' %}

{% block content %}
    <h1>Заявкa на ремонт</h1>    

    {% {% if user.role == 'CUSTOMER'  %}
    <div class="row">
        <div class="col-md-12">
            <a href="{% {% url 'repairs:create' %} %}" class="btn btn-success">Створити заявку</a>
        </div>
    </div>
    {% endif %} %}
    <hr>

    <div class="row mt-2">
        <div class="col-md-12">
            <table class="table table-success table-striped">
                <thead>
                    <tr>
                        <th>Order number</th>
                        <th>Locomotive</th>
                        <th>Repair place</th>
                        <th>Repair type</th>
                        <th>Date and time </th>
                        <th>Status</th>
                        <th>Open</th>
                    </tr>
                </thead>
                <tbody>
                    {% for repair in object_list %}
                    <tr>
                        <td>{{ repair.id }}</td>
                        <td>{{ repair.locomotive }}</td>
                        {% if repair.places_to_work %}
                            <td>{{ repair.places_to_work }}</td>
                        {% else %}
                            <td>Isn't defined</td>
                        {% endif %}
                        {% if repair.repair_type %}
                            <td>{{ repair.repair_type }}</td>
                        {% else %}
                            <td>Isn't defined</td>
                        {% endif %}
                        {% if repair.time_to_work %}
                            <td>{{ repair.time_to_work }}</td>
                        {% else %}
                            <td>Isn't defined</td>
                        {% endif %}
                        <td>{{ repair.get_status_display }}</td>
                        <td>{{ repair.get_absolute_url }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            
            </table>
        </div>
    </div>


{% endblock %}